version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - kafka-net
    depends_on:
      - kafka

  spark:
    build:
      context: .
      dockerfile: spark.Dockerfile
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./service-account.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    depends_on:
      - kafka
    networks:
      - kafka-net

networks:
  kafka-net: